# Generated by Django 4.1.1 on 2022-09-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('ano_lancamento', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('tempo', models.TextField()),
                ('sinopse', models.CharField(max_length=450)),
                ('imagem_pequena', models.URLField()),
                ('imagem_grande', models.URLField()),
                ('trailer', models.URLField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filmes.categoria')),
            ],
        ),
    ]
