# Generated by Django 4.1.1 on 2022-09-08 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='data_postagem',
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
    ]
