# Generated by Django 4.1.1 on 2022-09-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filmes_data_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='tempo',
            field=models.TimeField(),
        ),
    ]
