# Generated by Django 4.1.1 on 2022-09-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_alter_filmes_tempo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filmes',
            new_name='Filme',
        ),
    ]
